# Generated by Django 3.2.7 on 2021-10-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0002_movie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HR', 'Horror'), ('CM', 'Comedy')], max_length=2)),
            ],
        ),
    ]
