# Generated by Django 3.2.7 on 2021-10-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0005_rename_genre_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('HR', 'Horror'), ('CM', 'Comedy')], max_length=2, unique=True),
        ),
    ]
